services:
  postgres:
    image: postgres:16
    container_name: postgres_db2
    restart: always
    environment:
      POSTGRES_DB: entorn_db2
      POSTGRES_USER: entorn_user
      POSTGRES_PASSWORD: entorn_pass
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
